import logging
import traceback
from typing import Any, Dict

from fastapi import HTTPException, Request
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from api.utils.exception import ATSException


# ============================================================
# LOGGER
# ============================================================

logger = logging.getLogger(__name__)



# ============================================================
# ERROR RESPONSE BUILDER
# ============================================================

def build_error_response(
    status_code: int,
    error: str,
    message: str,
    details: Any = None,
) -> JSONResponse:
    """
    Build a consistent API error response.
    """

    response: Dict[str, Any] = {
        "status": "ERROR",
        "error": error,
        "message": message,
    }

    if details is not None:
        response["details"] = details

    return JSONResponse(
        status_code=status_code,
        content=response,
    )


# ============================================================
# HTTP EXCEPTION HANDLER
# ============================================================

async def http_exception_handler(
    request: Request,
    exc: HTTPException,
) -> JSONResponse:
    """
    Handle FastAPI HTTPException errors.

    Example:
        raise HTTPException(
            status_code=404,
            detail="Candidate not found"
        )
    """

    logger.warning(
        "HTTP error | method=%s path=%s status=%s detail=%s",
        request.method,
        request.url.path,
        exc.status_code,
        exc.detail,
    )

    return build_error_response(
        status_code=exc.status_code,
        error="HTTP_ERROR",
        message=str(exc.detail),
    )


# ============================================================
# VALIDATION ERROR HANDLER
# ============================================================

async def validation_exception_handler(
    request: Request,
    exc: RequestValidationError,
) -> JSONResponse:
    """
    Handle request validation errors generated by FastAPI/Pydantic.
    """

    errors = []

    for error in exc.errors():
        errors.append(
            {
                "field": ".".join(
                    str(location)
                    for location in error.get("loc", [])
                    if location != "body"
                ),
                "message": error.get("msg"),
                "type": error.get("type"),
            }
        )

    logger.warning(
        "Validation error | method=%s path=%s errors=%s",
        request.method,
        request.url.path,
        errors,
    )

    return build_error_response(
        status_code=422,
        error="VALIDATION_ERROR",
        message="Request validation failed",
        details=errors,
    )


# ============================================================
# GENERIC EXCEPTION HANDLER
# ============================================================

async def general_exception_handler(
    request: Request,
    exc: Exception,
) -> JSONResponse:
    """
    Handle unexpected application errors.

    Internal exception details are logged but are NOT returned
    to the client.
    """

    logger.error(
        "Unhandled exception | method=%s path=%s error=%s",
        request.method,
        request.url.path,
        str(exc),
    )

    logger.error(traceback.format_exc())

    return build_error_response(
        status_code=500,
        error="INTERNAL_SERVER_ERROR",
        message="An unexpected error occurred. Please try again later.",
    )

# ============================================================
# ATS EXCEPTION HANDLER
# ============================================================    
    
async def ats_exception_handler(
    request: Request,
    exc: ATSException,
) -> JSONResponse:
    """
    Handle application-specific ATS exceptions.
    """

    logger.warning(
        "ATS error | method=%s path=%s status=%s error=%s message=%s",
        request.method,
        request.url.path,
        exc.status_code,
        exc.error,
        exc.message,
    )

    return build_error_response(
        status_code=exc.status_code,
        error=exc.error,
        message=exc.message,
        details=exc.details,
    )