JD_HEADINGS = {
    "job_title",
    "company",
    "location",
    "job_summary",
    "responsibilities",
    "required_skills",
    "preferred_skills",
    "experience",
    "education",
    "employment_type",
    "soft_skills",
    "salary",
    "availability",
    "requirements",
}